Storage get count
ChristianAgha/AirBnB_clone_v3 pull request #1
Opened 2017-09-13 22:13 UTC by ChristianAgha

2017-09-13 22:55 UTC, johncoleman83 requested changes

2017-09-13 22:55 UTC, johncoleman83 commented on api/v1/__init__.py
> +from api.v1.views.index import *
it might be cleaner if you alphabetize this, just a suggestion?

2017-09-13 22:55 UTC, johncoleman83 commented on api/v1/app.py
> +    return storage.close()
please add comments for all functions

2017-09-13 22:55 UTC, johncoleman83 commented on api/v1/views/__init__.py
> +from api.v1.views import state
isn't this supposed to be a wildcard import?

2017-09-13 22:55 UTC, johncoleman83 commented on api/v1/views/index.py
> +    return make_response(jsonify({'status': 'OK'}))
please add comments for all functions

2017-09-13 22:55 UTC, johncoleman83 commented on models/engine/db_storage.py
> +        if cls:
What if `id` is None?

2017-09-13 22:55 UTC, johncoleman83 commented on models/engine/db_storage.py
> +            obj_class = self.__session.query(self.CNC.get(cls)).all()
No need to query here, you can simply use the `.all()` function on `self`...  Also, remember `.all()` is setup to take `cls` as an argument, if you use that argument you will not have to rewrite so much code.

2017-09-13 22:55 UTC, johncoleman83 commented on models/engine/db_storage.py
> +        all_objects = self.all(cls)
You need to properly handle when `cls = None`

2017-09-13 22:55 UTC, johncoleman83 commented on models/engine/file_storage.py
> +        if cls:
Good update here!

2017-09-13 22:55 UTC, johncoleman83 commented on models/engine/file_storage.py
> +    def count(self, cls=None):
Same comments as other Storage engine apply here

2017-09-13 22:57 UTC, johncoleman83 commented
Great updates, please review my comments and respond, then I'll accept your PR, also please add the proper file `code_review.txt` with your name in it, since I reviewed you.

2017-09-13 23:23 UTC, johncoleman83 approved these changes

2017-09-13 23:39 UTC, clturner commented on api/v1/app.py
> +from api.v1.views import app_views, states
Please alphabetize the imports

2017-09-13 23:39 UTC, clturner commented on api/v1/views/index.py
> +from flask import Blueprint, render_template, make_response, jsonify
alphabetize imports

2017-09-13 23:39 UTC, clturner commented on api/v1/views/states.py
> +from flask import Flask, jsonify, Blueprint, make_response, render_template
alphabetize imports

2017-09-13 23:39 UTC, clturner commented on api/v1/views/states.py
> +
add code for delete function to delete state matching id

2017-09-13 23:39 UTC, clturner commented on api/v1/views/states.py
> +    return jsonify(all_st)
change to:    return jsonify([st.to_json() for st in storage.all("State").values()]) to make one line.

2017-09-13 23:44 UTC, merged

2017-09-15 23:57 UTC, papamuziko commented on models/engine/file_storage.py
> +#!/usr/bin/python3#!/usr/bin/python3
Heum...